### PR TITLE
refactor(post): Make post script pluggable.

### LINKED ISSUE #149: Refactor Post Script into Plugin
Refactor the `semantic-release post` script to be pluggable. The end goal is to support alternative SCM platforms to GItHub through a pluggable `post` script.

### PR DESCRIPTION
**Pull request by hbetts**
Refactor the post script so that it's pluggable. Move the existing
functionality of the post script into a `github-release` plugin, and
make that plugin the default for the post lifecycle stage.

By making the post script pluggable, other SCM platforms can be
supported in addition to GitHub.

Closes #149 

* [x] Update `README.md` documentation to reflect refactor.
* [x] Actually test using GitHub/Travis-CI setup.
* [x] Get 100% code coverage by adding branch testing for error cases.

### CODE REVIEW

**Comment by hbetts** [comment]
I've completed the following:

* Rebase
* Update README
* 100% code coverage on new code
* Verified refactored code can correctly publish release to GitHub: https://github.com/hbetts/post-test/releases

Could I get some feedback please, and if nothing needs changing, can this get merged?

**Comment by boennemann** [comment]
Hey @hbetts,

sorry for the outstanding review. I'm currently trying to rethink the way semantic-release could work, especially it's architecture and plugin system. See https://gist.github.com/boennemann/ac06b7f8bcf50510ffa1 for some thoughts.

I can't find anything bad with your PR, but I'm a little hesitant to merge it, without knowing whether that's the right direction in general. Like, I don't want to introduce a new feature that I'm already thinking of deprecating.

I'm really sorry, because I currently don't have the time this project would deserve and need, to move forward on these ideas, but I'm trying to get back to it as soon as I possibly can.

Best,
Stephan

**Comment by hbetts** [comment]
@boennemann no problem. Thank you for letting me know about your architecture re-work.

Just as a little background, I'm managing about ~35 npm projects that have contributions from several other people. I end up spending quite a bit of time using a `release-it` like setup to manually publish new versions, and then post back to issues and merge requests with the version number. That's why I'm working towards implementing a GitHub notifier: https://github.com/hbetts/semantic-release-github-notifier

**Comment by hbetts** [comment]
As this pull request has been sitting here for a while, I'm going to go ahead and close it out.

**Pull request closed without merging**
