### PR TITLE
fix(definitions): Repository documentation links

### PR DESCRIPTION
**Pull request by ffflorian**
This PR will
- fix the documentation links to this repository by adding the appropriate numbers

### CODE REVIEW

**Comment by pvdlg** [comment]
This commit should have been a `docs` not a `fix`...

**Comment by ffflorian** [comment]
@pvdlg IMO it's a fix since it's not an update of a documentation file but fixing a broken link. WDYT?

**Comment by pvdlg** [comment]
oh yes indeed. My bad, I though the PR was modifying the links in the docs and not in the code.

**Comment by ffflorian** [comment]
Alright :)

**Pull request merged**
