### PR TITLE
fix(repositoryUrl): on beta repositoryUrl needs auth for pre-release flows

### PR DESCRIPTION
**Pull request by jmodjeski75**
Fixing issue with authentication for repositoryUrl not being used for prerelease workflow

### CODE REVIEW

**Comment by jmodjeski75** [comment]
possible fix for #1170 #1156

**Comment by pvdlg** [comment]
I'm not sure those changes were necessary. It seems the change is to use the authenticated URL to call `git ls-remote`. However this command should work without authentication, as the the CI was able to clone the repo.

My understanding is that if `git clone` works then `git ls-remote` should work as well.
How come the repo was cloned successfully but the branches couldn't be read on the remote?

**Comment by pvdlg** [comment]
Also this commit make the build fail.

**Comment by gr2m** [comment]
Let’s revert and then try again

**Comment by pvdlg** [comment]
The build error happens only on Travis though, not locally.
I'll investigate a bit more and if I can't find a solution I'll revert and work on it later.

**Comment by jmodjeski75** [comment]
> I'm not sure those changes were necessary. It seems the change is to use the authenticated URL to call `git ls-remote`. However this command should work without authentication, as the the CI was able to clone the repo.
> 
> My understanding is that if `git clone` works then `git ls-remote` should work as well.
> How come the repo was cloned successfully but the branches couldn't be read on the remote?

@pvdlg 
Are you using a private repository? `git ls-remote` for a private repository requires auth

**Comment by pvdlg** [comment]
> Are you using a private repository? git ls-remote for a private repository requires auth

Yes but that auth should already be provided one way or another by your CI (ssh key or environment variable or other).

How could your CI run `git clone` otherwise?
What I understand is how `git clone` could work while `git ls-remote` doesn't?

**Comment by jmodjeski75** [comment]
`git clone <with-auth-url>`

**Comment by pvdlg** [comment]
The `git clone` is done by your CI way before semantic-release run.

Where does the `<with-auth-url>` come from? If your CI uses an authenticated URL to clone why doesn't it set that URL in the `origin` of the repo.
How do you end up in the situation of your CI running `git clone <with-auth-url>` then setting the non authenticated URL as the `origin` of the clone?

Before this PR, the `git ls-remote` was called with `origin` in order to use whatever remote URL the CI uses which should at least gives read permission.

**Comment by jmodjeski75** [comment]
> why doesn't it set that URL in the `origin` of the repo.

Where is this documented?

> Before this PR, the `git ls-remote` was called with `origin` in order to use whatever remote URL the CI uses which should at least gives read permission.

no it _assumed_ there was a remote named `origin`

**Comment by pvdlg** [comment]
> Where is this documented?

What do you mean? In the your CI doc? I don't know.
It's the way that every CI I tested works. It doesn't make much sense for the CI to set the `origin` as an URL that doesn't works.

What CI are you using?

> no it assumed there was a remote named origin

I don't know is *assumed* is the right term here. Every repo on which semantic-release would run is a local clone and calling `git clone <some_url>` setts the `origin` to <some_url>.

It seems your CI, for some reason calls `git clone <auth_url>` and then `git remote set-url origin <non_auth_url>`. I don't see what's the point of doing that.

**Comment by jmodjeski75** [comment]
> What do you mean? In the your CI doc? I don't know.

Here in this repository, no where in the docs does it indict having to call `git remote add origin <auth_url>` if this were true, this would not be [necessary](https://github.com/semantic-release/semantic-release/blob/master/index.js#L6)2. If the consumer, CI or not, should explicitly have a `remote` named `origin` and set to the appropriate url for both `git fetch` and `git push` it should be clearly documented.
But based on the documentation [here](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md#git-authentication-with-ssh-keys) that convenience of figuring out which auth scheme to use and what the correct repository url with auth for `git fetch` and `git push` should be is provided but if that is incorrect, remove, close the loop.

**Comment by pvdlg** [comment]
I tested semantic-release on something like 20 different CI. All of them set the `origin` of the cloned repo as a URL that has read access to the repo. Some use and ssh key, some other use use an URL formatted with credentials, but they all make sure you can run git commands that read the repo without having to do anything (if you don't specify a URL `git` will use `origin` by default).

It seems your CI behave differently. Again, what CI are you using?

**Comment by jmodjeski75** [comment]
> (if you don't specify a URL `git` will use `origin` by default).

sure but the repository **may not** have a `remote` called `origin` but I digress. See [git remove](https://git-scm.com/docs/git-remote) `git remove remove origin` or `git remove rm origin`

> It seems your CI behave differently. Again, what CI are you using?

I am using Jenkins
#1156 - TeamCity
#1170 - a docker based CI of some kind

**Comment by alexan** [comment]
yes jenkins uses different git authentication, for checkout and for what is available, when you use git binary directly

**Comment by alexan** [comment]
I don't know if these changes are connected. But after updating and usage of beta-20 in a existing project I got another error: https://github.com/semantic-release/semantic-release/issues/1199

**Pull request merged**
