### PR TITLE
fix: require Node.js >=8.16

### PR DESCRIPTION
**Pull request by pvdlg**

### CODE REVIEW

**Comment by tuckbick** [comment]
Seems like this should have been a breaking release 😢

**Comment by pvdlg** [comment]
Yes it should have but we've decided to make an exception and avoid a breaking change just for changing the min requirement from 8.3 to 8.16...

**Comment by chrskrchr** [comment]
> Yes it should have but we've decided to make an exception and avoid a breaking change just for changing the min requirement from 8.3 to 8.16

The irony of `semantic-release` not following semantic versioning... 😄

**Comment by gr2m** [comment]
Only the Sith deal in absolutes 😉

**Pull request merged**
