### PR TITLE
feat: add main branch to default release branch config

### PR DESCRIPTION
**Pull request by timfisher**
I had a confusing error message saying 1 to 3 branches were required when I had the following config:

```
module.exports = {
  release: { branches: 'main' },
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    ['@semantic-release/npm', { npmPublish: false }],
    '@semantic-release/github',
  ],
}
```

 [semantic-release] » ×  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).   

This may occur if your repository does not have a release branch, such as master.

Although the config is incorrect adding main to the default config/ error message would help people in a similar situation who have missing config or incorrect config and a default main branch provided with github

### CODE REVIEW

**Review by kadirselcuk — APPROVED** [review]

**Review by styfle — APPROVED** [review]
Looks good to me 👍

**Comment by alexw10** [comment]
Is there an ETA on when this will be released? We have a new Azure devops git that we are using and it is defaulting to just have a main branch and getting this error:
[4:09:35 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].


Or is there a workaround adding "master" to my list in package.json releases does not seem to work gives this message:
```    "
branches": [
      "master",
      "main"
    ],
```

**Comment by gr2m** [comment]
> You might want to add `main` to the [usage docs](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches): And since it is the new Github default branch, looking into the future, it would make things a lot clearer if it were added to the [README](https://github.com/semantic-release/semantic-release#triggering-a-release)

That's a good idea, PR welcome!  I'd document it in the usage docs and then reference it from the README?

**Comment by otorrillas** [comment]
> > You might want to add `main` to the [usage docs](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md?rgh-link-date=2021-06-03T18%3A10%3A03Z#branches): And since it is the new Github default branch, looking into the future, it would make things a lot clearer if it were added to the [README](https://github.com/semantic-release/semantic-release#triggering-a-release)
> 
> That's a good idea, PR welcome! I'd document it in the usage docs and then reference it from the README?

We've just opened one pull request to document it in @timfisher fork https://github.com/timfisher/semantic-release/pull/1

**Comment by timfisher** [comment]
I added @otorrillas docs looks like we need a maintainer to approve running the workflow now

**Comment by otorrillas** [comment]
@gr2m would you mind having a look now that it includes a docs update? 😄

**Comment by nornagon** [comment]
Friendly ping :) would be great to get this merged!

**Comment by therussiankid92** [comment]
@timfisher @styfle second friendly ping - with what can we contribute to make this change move forward?

**Comment by gr2m** [comment]
I want us to finish the transition to ES Modules first: https://github.com/semantic-release/semantic-release/issues/2133. Once we have that, this issue is high on my priority. It will take a while to thoroughly test it.

**Comment by r4j4h** [comment]
I think this might be preferable so as to support both:

```
  branches: [
    '+([0-9])?(.{+([0-9]),x}).x',
    '(master|main)',
    'next', 'next-major', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}
  ],
```

Note that `master|main` does not work, must have the parenthesis around it for semantic-release to treat as RegExp.

**Comment by nickmccurdy** [comment]
It seems like there's still more work to be done on the ES module conversion. Can we please get this merged in the interim? I'd argue it's already being sufficiently tested considering how many repositories are already using this configuration.

**Review by nickmccurdy — APPROVED** [review]

**Comment by Aeolun** [comment]
@travi @gr2m Is this something that can maybe be merged? We've been dealing with this nonsense for literal years now. While I completely understand that you might have no time for a migration to ESM, it is incredibly frustrating that a package so central to my publishing workflow does not work with the default branch of my chosen VCS.

**Comment by gr2m** [comment]
I hear you and agree. My life situation doesn't leave much time for semantic-release righ now, but this is my top priority as well. I'll talk to @travi about it this Friday, if anyone is interested in taking the lead on getting this feature shipped, please let us know. Really sorry about how long this takes, it frustrates me in my own usage of semantic-release as well.

**Comment by travi** [comment]
so sorry that it has taken so long to get this moving forward. this is a change that is important to us, so i'm hoping we can get this merged soon. thanks a ton for all the work you put into this @timfisher, especially going beyond the functional change and tracking down the details throughout the docs to update along with it.

would you be willing to update this branch with the latest changes? i think this looks like it should get us to the point of getting it merged

**Comment by timfisher** [comment]
> so sorry that it has taken so long to get this moving forward. this is a change that is important to us, so i'm hoping we can get this merged soon. thanks a ton for all the work you put into this @timfisher, especially going beyond the functional change and tracking down the details throughout the docs to update along with it.
> 
> would you be willing to update this branch with the latest changes? i think this looks like it should get us to the point of getting it merged

Sure mate I will update this weekend 👍

**Comment by timfisher** [comment]
@travi Should be good now 👍 Some CLI tests still reference master so I didn't know whether to duplicate them or not. I left them out. Thanks all.

**Review by travi — APPROVED** [review]

**Comment by travi** [comment]
released to the beta channel to start with. would appreciate feedback from folks following this thread in case this introduces any surprises. hoping to promote to stable within a week or so, so feedback from folks that have tried it out would help with confidence for promoting.

**Comment by Aeolun** [comment]
Awesome, I’m update my packages and see if anything breaks.

**Comment by gr2m** [comment]
wohoo looks good when testing it locally! I'll test it in production as soon as the next opportunity arises. Thank you all for seeing this through ❤️

**Comment by gr2m** [comment]
First test in production: [success](https://github.com/octokit/auth-app.js/pull/606#issuecomment-2103327532)

**Comment by travi** [comment]
PR to promote to stable: https://github.com/semantic-release/semantic-release/pull/3300

**Pull request merged**
