### PR TITLE
docs: add comment about publishing with ssh keys

### PR DESCRIPTION
**Pull request by ev1stensberg**
As stated in #782

### CODE REVIEW

**Comment by pvdlg** [comment]
The note added is not accurate, as the SSH keys are sufficient for the base functionalities of semantic-release core. An API is required only when using a plugin that requires it and would be mentioned in the plugin doc.

Could you replace the note with:

```md
**Note:** SSH keys allow to push the [Git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) associated to the released version. Some plugins might also require an API token. See each plugin documentation for additional information.
```

**Comment by ev1stensberg** [comment]
gotcha, updated now

**Comment by ev1stensberg** [comment]
There we go 👍

**Comment by pvdlg** [comment]
Thanks

**Pull request merged**
