### PR TITLE
test(mockserver): switched to the modern mockserver/mockserver image to get multi-arch support

### LINKED ISSUE #2478: Integration tests fail to execute properly on ARM CPU architecture
### Current behavior

the tests timeout do to docker failing to start the [docker-gitbox image](https://github.com/semantic-release/semantic-release/blob/9589a96239826abe9b07e8deffcc7d8aeb9c2e40/test/helpers/gitbox.js#L6) that we use. this is due to it not supporting the ARM architecture. 

I made some progress resolving the architecture limitation in https://github.com/semantic-release/docker-gitbox/issues/4, but have not resolved all of the issues to enable the integration tests to run successfully in this project yet.

```
✖ integration › before hook Rejected promise returned by test
✖ integration › after.always hook Rejected promise returned by test
✖ 14 tests remaining in test/integration.test.js
```

```
integration › before hook

  Rejected promise returned by test. Reason:

  Error {
    address: '/var/run/docker.sock',
    code: 'ENOENT',
    errno: -2,
    syscall: 'connect',
    message: 'connect ENOENT /var/run/docker.sock',
  }



  integration › after.always hook

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'Cannot read properties of undefined (reading \'stop\')',
  }

  › Object.stop (test/helpers/gitbox.js:42:19)
  › test/integration.test.js:62:29

  ─

  2 hooks failed
```

### Expected behavior

the full test suite should execute without timing out. that means that the docker images must be usable on both x86 and ARM architectures. 

this could be enabled by updating https://github.com/semantic-release/docker-gitbox to work properly or by abandoning that image and finding a more modern one that is supported by the community rather than this team, but still satisfies the needs we have for these tests.

### `semantic-release` version

latest

### CI environment

local

### Plugins used

_No response_

### `semantic-release` configuration

N/A

### CI logs

see details from https://github.com/semantic-release/docker-gitbox/issues/4

### PR DESCRIPTION
**Pull request by travi**
fixes #2478

### CODE REVIEW

**Comment by travi** [comment]
tested on my M1 Macbook Pro and this enables `npm test` to fully work

**Comment by gr2m** [comment]
I see these errors locally

```
  integration › before hook

  Rejected promise returned by test. Reason:

  Error {
    address: '/var/run/docker.sock',
    code: 'ENOENT',
    errno: -2,
    syscall: 'connect',
    message: 'connect ENOENT /var/run/docker.sock',
  }



  integration › after.always hook

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'Cannot read properties of undefined (reading \'stop\')',
  }

  › Object.stop (test/helpers/gitbox.js:42:19)
  › test/integration.test.js:62:29
```

But might be something odd with my local setup? I can investigate that another time, we can merge it to unblock your work

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
actually nevermind, restarting Docker fixed it for me 👍🏼

**Comment by travi** [comment]
> I see these errors locally

i've seen those errors when a previous version of a container was not stopped correctly from a previous run. if you stop any running containers in docker and try again, i hope you'll have better results. there may be a better way for us to handle that situation gracefully, but i agree that improving this goes beyond this PR

**Pull request merged**
