### PR TITLE
docs: semantic-release SVG logo

### LINKED ISSUE #1714: Current Logo in SVG?
Do you have the current logo in SVG format available? :)

https://gblobscdn.gitbook.com/spaces%2F-LGsE7zdvzHI5cG-XV6p%2Favatar.png

### PR DESCRIPTION
**Pull request by bromso**
closes #1714

I recreated the logo and used this image as a reference: https://gblobscdn.gitbook.com/spaces%2F-LGsE7zdvzHI5cG-XV6p%2Favatar.png

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Thank you so much!

**Comment by bromso** [comment]
It is I that should bow & say thank you so much for such an awesome tool! 😄

**Comment by mxdvl** [comment]
Nice addition, @bromso. Here are two small things you might not know:

1. You can strip your SVGs of all vendor-specific information (in you case, the fact that it was created with Sketch, for example), by using a tool like `svgo` or the online version [svgomg][].

2. You can embed images directly in your PR by using the markdown syntax `image`, like so: semantic-release logo PNG

[svgomg]: https://jakearchibald.github.io/svgomg/

**Comment by gr2m** [comment]
@mxdvl thanks for sharing these insights! Could you send a PR to update the SVG?

**Pull request merged**
