### PR TITLE
Allow custom arguments for finding git commits

### PR DESCRIPTION
**Pull request by sagarjauhari**
Use case: If we have a release branch `release-1` which has been merged into
master and on the master branch we want semantic-release to consider only the
commits which are exclusive to the `master` branch since 'A', then the output
should only include the commits B, C, merged, E and F.
Git history:

```
-----------------------------
A-B-C-merged-E-F....(master*)
 \   /
  P-Q...........(release-1.0)
-----------------------------
```

### CODE REVIEW

**Comment by pvdlg** [comment]
Can you clarify what you try to achieve?
What is this `release-1.0` branch? Is it where you run semantic-release to make releases? Do you also make releases from `master`?
What's the point of ignoring some commits to make the release decision?

**Comment by sagarjauhari** [comment]
Great questions @pvdlg . The use case here is to
1. Run semantic-release on all branches
1. Maintain several 'release' branches which are regularly up-merged all the way up to `master`
1. When a new release is cut (say `release-2.0` from master) semantic-release should only analyze commits which were made exclusively on the master branch (A, B, C, D, E) and ignore commits which were up-merged from other release branches (P, Q).

image

**Comment by pvdlg** [comment]
> When a new release is cut (say release-2.0 from master) semantic-release should only analyze commits which were made exclusively on the master branch (A, B, C, D, E) and ignore commits which were up-merged from other release branches (P, Q).

But why? What problem are you trying to work around?
I don't understand what you want to ignore commits that are in the history of a branch. The code resulting of those commits will be part of the release, ignore them doesn't seems to make any sense.

Can you provide a step by step scenario that illustrate what you try to achieve and explain what problem you are facing?

**Comment by sagarjauhari** [comment]
One of the reasons why I need to do this is:

I use semantic-release to  generate release notes and separate release notes are generated for each release branch. If I don't ignore the commits up-merged from other branches, then the release notes of a newly cut release-branch uses commits of *every* release branch that has commits merged to master. For the release notes of a new release, I want to use the commits which were exclusive to the master branch (because the other changes which were up-merged would have been included in the release notes of their respective release branches)

So, although the default behaviour makes sense (use all the commits in your git history), my use case is to generate a set of release notes for each release branch that I'm maintaining. Which means: I need a way to filter out the commits.

**Comment by pvdlg** [comment]
If you make a release on a branch, a tag is created. when you merge those commit to another branch the tag should follow, so when semantic-release runs it will consider only the commits since the last tag, therefore no commit will be included the release note of two different releases.

So I don't understand how you can end up in the situation you describe.

**Comment by sagarjauhari** [comment]
Well, in the case below, when I create the new release (release-2.0) I need to be able to only use the commits A-E and not P,Q. The issue is that because the release branches are regularly merged to master the commits from release-branches are *interleaved* with the commits on master and I need a way to filter out only the commits that were made exclusively on master. 

image

**Comment by pvdlg** [comment]
Please provide a step by step way to reproduce what you are talking about.
Something like:
- `git checkout some-branch`
- `git commit -m something`
- run semantic-release on branch some-branch
- `git merge ....`
- etc...

And explain what yu

**Comment by pvdlg** [comment]
Closing as no response provided

**Pull request closed without merging**
