### PR TITLE
chore: clean and strip SVG logo

### PR DESCRIPTION
**Pull request by mxdvl**
This result is obtained using [svgomg][] and a precision of `0`. As the `viewBox` is already quite large at 500x500 pixels, sub-pixel precision can be discarded.

As discussed in https://github.com/semantic-release/semantic-release/pull/1715#issuecomment-754077646.

[svgomg]: https://jakearchibald.github.io/svgomg/

### CODE REVIEW

**Comment by mxdvl** [comment]
I’m not sure why the `viewBox` is not square, this is only based on @bromso’s original tracing.

**Comment by gr2m** [comment]
I don't think it was square before? Can you make it square?

**Review by gr2m — APPROVED** [review]
Thanks Max!

**Comment by gr2m** [comment]
let me know when you are done working on it

**Comment by mxdvl** [comment]
All done, I made it 500x500, and centered:

**Review by DvalCaruso — COMMENTED** [review]
Duplicate of #

**Comment by mxdvl** [comment]
@DvalCaruso care to elaborate?

**Pull request merged**
