### PR TITLE
Allow running semantic release from node

### PR DESCRIPTION
**Pull request by meldiner**

### CODE REVIEW

**Comment by camwest** [comment]
@boennemann mind taking a look at this one?

**Comment by PatrickHeneise** [comment]
What does this do?

**Comment by meldiner** [comment]
we use semantic release by requiring it as a module and not using its cli. this PR is for allowing this type of usage.

**Comment by gr2m** [comment]
Hey friends 👋 Sorry it took so long to get back to you 😞 I [recently joined as maintainer](https://github.com/semantic-release/semantic-release/issues/411) and would like to help you get this merged. I don’t see any reason not to support to use semantic-release as package by moving out all CLI related logic 👍 

Could you please update the PR on the latest master and let me know once you did? And I’d also like to ask you to add a test of using `require('semantic-release')` as a package

I’d be happy to make a proper review then

**Comment by gr2m** [comment]
thanks Ron, I can take it from here. I’ll be travelling next week but will have time after

**Pull request closed without merging**
