### PR TITLE
fix: use one note reference per tag to prevent conflicts

### LINKED ISSUE #1613: pushNotes fails when builds run in parallel
## Current behavior

If two copies of `semantic-release` run concurrently, they can [trample each other's release notes](https://github.com/bee-queue/arena/runs/952013202?check_suite_focus=true) (stack trace excerpted below). I wonder if there's any way to configure a unique set of refs based on some CI-dependent metadata to avoid conflicts like these. This seems to have occurred because I had the primary branch and a maintenance branch attempt to release at the same time.

<details>
<summary>Stack trace</summary>

```
2020-08-06T02:42:23.3816391Z [2:42:23 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push https://x-access-token:[secure]@github.com/bee-queue/arena.git refs/notes/semantic-release
2020-08-06T02:42:23.3817588Z To https://github.com/bee-queue/arena.git
2020-08-06T02:42:23.3818767Z  ! [rejected]        refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)
2020-08-06T02:42:23.3819565Z error: failed to push some refs to 'https://github.com/bee-queue/arena.git'
2020-08-06T02:42:23.3820132Z hint: Updates were rejected because the remote contains work that you do
2020-08-06T02:42:23.3820628Z hint: not have locally. This is usually caused by another repository pushing
2020-08-06T02:42:23.3821381Z hint: to the same ref. You may want to first integrate the remote changes
2020-08-06T02:42:23.3822140Z hint: (e.g., 'git pull ...') before pushing again.
2020-08-06T02:42:23.3822885Z hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2020-08-06T02:42:23.3823762Z     at makeError (/home/runner/work/arena/arena/node_modules/execa/lib/error.js:59:11)
2020-08-06T02:42:23.3824236Z     at handlePromise (/home/runner/work/arena/arena/node_modules/execa/index.js:114:26)
2020-08-06T02:42:23.3825032Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-08-06T02:42:23.3825765Z     at async pushNotes (/home/runner/work/arena/arena/node_modules/semantic-release/lib/git.js:248:3)
2020-08-06T02:42:23.3826681Z     at async run (/home/runner/work/arena/arena/node_modules/semantic-release/index.js:194:5)
2020-08-06T02:42:23.3827442Z     at async module.exports (/home/runner/work/arena/arena/node_modules/semantic-release/index.js:260:22)
2020-08-06T02:42:23.3828211Z     at async module.exports (/home/runner/work/arena/arena/node_modules/semantic-release/cli.js:55:5) {
2020-08-06T02:42:23.3829096Z   shortMessage: 'Command failed with exit code 1: git push https://x-access-token:[secure]@github.com/bee-queue/arena.git refs/notes/semantic-release',
2020-08-06T02:42:23.3829917Z   command: 'git push https://x-access-token:[secure]@github.com/bee-queue/arena.git refs/notes/semantic-release',
2020-08-06T02:42:23.3830363Z   exitCode: 1,
2020-08-06T02:42:23.3830725Z   signal: undefined,
2020-08-06T02:42:23.3831086Z   signalDescription: undefined,
2020-08-06T02:42:23.3831611Z   stdout: '',
2020-08-06T02:42:23.3832277Z   stderr: 'To https://github.com/bee-queue/arena.git\n' +
2020-08-06T02:42:23.3833027Z     ' ! [rejected]        refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)\n' +
2020-08-06T02:42:23.3834290Z     "error: failed to push some refs to 'https://github.com/bee-queue/arena.git'\n" +
2020-08-06T02:42:23.3835034Z     'hint: Updates were rejected because the remote contains work that you do\n' +
2020-08-06T02:42:23.3835975Z     'hint: not have locally. This is usually caused by another repository pushing\n' +
2020-08-06T02:42:23.3836890Z     'hint: to the same ref. You may want to first integrate the remote changes\n' +
2020-08-06T02:42:23.3837566Z     "hint: (e.g., 'git pull ...') before pushing again.\n" +
2020-08-06T02:42:23.3838266Z     "hint: See the 'Note about fast-forwards' in 'git push --help' for details.",
2020-08-06T02:42:23.3838686Z   failed: true,
2020-08-06T02:42:23.3839662Z   timedOut: false,
2020-08-06T02:42:23.3840032Z   isCanceled: false,
2020-08-06T02:42:23.3840303Z   killed: false
2020-08-06T02:42:23.3840720Z }
```
</details>

## Expected behavior

No failure, no concurrent use of the same resource.

## Environment

- **semantic-release** version: 17.1.1
- CI environment: GitHub actions
- Plugins used: [several](https://github.com/bee-queue/arena/blob/07393fa293882d0ca90008fca4e00310a547526b/package.json#L21-L27), but the stack trace originates in `semantic-release` core
- **semantic-release** configuration: [release.config.js](https://github.com/bee-queue/arena/blob/master/release.config.js)
- [CI logs](https://github.com/bee-queue/arena/runs/952014075?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by KillianHmyd**
## Current behavior

All notes are pushed under the reference `semantic-release` because of that, if from two different branches and channels a release is performed at the same time the release would fail on one of them with this error : 
```
 ! [rejected]        refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)
```

## New behavior

Instead of using only one note reference we would use one per tag, this way we could not have any conflict between multiple channels.
This change should be retro-compatible and doesn't need a migration.

resolves #1613

### CODE REVIEW

**Comment by KillianHmyd** [comment]
This PR should fix https://github.com/semantic-release/semantic-release/issues/1613

**Comment by KillianHmyd** [comment]
Hello @gr2m, is there a chance to move forward on this PR

**Comment by KillianHmyd** [comment]
Hi @gr2m, would you have some time to look at the PR ? 🙏🏾

**Comment by KillianHmyd** [comment]
Hello @gr2m , @travi, @pvdlg , any chance that you could give it a look 🙏🏾 ?

**Review by dgroh — APPROVED** [review]

**Comment by KillianHmyd** [comment]
Kindly reminder @travi 🙏🏾 Could we have a review on this PR please

**Comment by Renatopster** [comment]
Also waiting on this

**Comment by gr2m** [comment]
We get to it. If you could please add a 👍🏼 emoji to the pull request instead of basically adding +1 comments, we'd appreciate it. It's only causing noise for us and everyone else watching the pull request.

We cannot give you an ETA but you can see more activity happening in @semantic-release again, so hopefully not to far out. We are close to wrapping up [the transition to ES Modules](https://github.com/semantic-release/semantic-release/issues/2133) which is our primary focus right now.

**Comment by mcmiddle592** [comment]
Hello, just wanted to mention that I pulled in @KillianHmyd branch into my release pipeline and it resolved my issues when releasing defect fixes to multiple Long Term Support (LTS) branches in a single repo at once. Without the changes I get the same error mentioned in the PR description whenever semantic-release runs on multiple branches in parallel on a single repo. 

For those curious on how I did the test, I had to pull in the GitHub branch through npm like so:
`npm i https://github.com/KillianHmyd/semantic-release.git#fix/notes-concurrency --save-dev --legacy-peer-deps`

I had to add the following to my .npmrc file while testing the GitHub branch due to the branch not matching some of my peer dependency requirements mentioned in my package-lock.json: `legacy-peer-deps=true`. You can add this directly into your npm commands in your pipeline, but editing the .npmrc was the lowest impact change I could find.

Screenshot below is the error you get without this workaround:
image

**Review by travi — APPROVED** [review]
sorry for the delayed merge. thanks for the contribution!

**Comment by travi** [comment]
please give the pre-release a try and report any complications. hoping to promote to stable in about a week

**Pull request merged**
