### PR TITLE
Use normalize-package-metadata to normalize package.json info

### PR DESCRIPTION
**Pull request by hawkrives**
Part of #104.

Which test file should I modify to add tests for this?

It currently passes on my machine,

### CODE REVIEW

**Comment by hbetts** [comment]
:+1: 

@hawkrives could you rebase your branch?

**Comment by hawkrives** [comment]
I think I've just rebased. Fingers crossed that the tests still pass.

**Comment by hbetts** [comment]
:+1: Looks great!

**Comment by hawkrives** [comment]
Thanks!

**Pull request merged**
