### PR TITLE
fix: Resolve problems with setting options.ci and .noCi

### PR DESCRIPTION
**Pull request by EvanCarroll**
This was covered in #1696. This is an attempt to resolve all outstanding
known issues between ci and noCi from command line and env.

### CODE REVIEW

**Comment by travi** [comment]
the current documentation for the `ci` and `no-ci` flags can be found at https://semantic-release.gitbook.io/semantic-release/usage/configuration#ci.

while it is true that `--no-ci` is equivalent `--ci false`, it is not intended to force the ci detection to be `true`. from those docs, it is mentioned that this is intended for to
> skip Continuous Integration environment verifications. This allows for making releases from a local machine.
(which is possible, but not recommended for normal use)

in short, it is used to _override_ the automatic CI service detection in areas like https://github.com/semantic-release/semantic-release/blob/0f0c650b41764d1a3deb33631147c7ca0e39fe59/index.js#L32-L34

in addition, the `CI` environment variable is not significant to `semantic-release` for similar reasons. 

instead, the intention is for [env-ci](https://github.com/pvdlg/env-ci) to [detect the CI environment](https://github.com/semantic-release/semantic-release/blob/0f0c650b41764d1a3deb33631147c7ca0e39fe59/index.js#L29). as described in https://semantic-release.gitbook.io/semantic-release/developer-guide/plugin#context, `env-ci` normalizes some of the CI provided information for consumption by semantic-release. if you are running in a CI environment that should be detected but is not, you could consult the env-ci project to better understand why your environment is not being detected properly.

**Comment by EvanCarroll** [comment]
That's not entirely clear me,

> while it is true that --no-ci is equivalent --ci false, it is not intended to force the ci detection to be true

The behavior of `--no-ci false` is not documented anywhere on that page are we inferring desired behavior from that code block, or should we documented this somewhere? It's also not clear to me why without specifying `--ci` or `--no-ci` I would want to run in dry-run mode?

The part about not reading `env["ci"]` directly makes sense in light of that abstraction library. But it doesn't make sense to ignore that environmental information when you trying to synchronize a global app state into options. At some point your users are just going to be concerned with whether or not they're running in ci mode, and what should they check: (A) just `options.ci`, (B) both `options.ci` and `options.notCi`, (C) `options.ci` and `options.notCi` and `env-ci`? Where does this get synthesized into a global state? If people are supposed to write code like `(!isCi ... && !options.noCi)` then I think we should document this.

**Comment by travi** [comment]
we have plenty of gaps in our documentation, so there is always room for improvement. if you would like to help us improve the documentation around this behavior, we would welcome a PR for review.

**Comment by EvanCarroll** [comment]
I think I have to maintain my own fork at this point. Feel free to close out my other patches.

**Pull request closed without merging**
