### PR TITLE
fix(deps): update find-versions to v5.0.0

### LINKED ISSUE #2424: upgrade dependency find-versions
The current release of semantic-release (19.0.2) uses `find-versions` 4.x as a dependency. This library is indicated by github's dependabot to have security vulnerabilities originating in the required `semver-regex` library, which has version 3.1.2.

Could you please consider updating to `find-versions` 5.x which currently uses a good `semver-regex` version (4+)

### PR DESCRIPTION
**Pull request by pierluigilenoci**
Fixes #2424

This PR is a copy of #2452 but rebased with the latest master.

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@faves4less @travi @gr2m could you please take a look?

**Review by AalOsman — APPROVED** [review]

**Comment by gr2m** [comment]
This is blocked by https://github.com/semantic-release/semantic-release/issues/2133

Please stop pinging folks, we get to it when we get to it.

**Comment by travi** [comment]
this has been resolved by https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0

**Pull request closed without merging**
