### PR TITLE
docs(Plugin Developer Guide): More detailed lifecycle list and context descriptions

### PR DESCRIPTION
**Pull request by XC-**
This commit will improve the following in the Plugin developer guide:
  * Lifecyle list more complete (previous was missing some lifecycles)
  * Context object has been now described in more detail per lifecycle
  * Some readability/maintainability fixes to the markdown file itself
    to make it easier to edit and read in an editor.

### CODE REVIEW

**Comment by XC-** [comment]
@gr2m @travi @pvdlg Any comments on this?

**Review by gr2m — COMMENTED** [review]
could you please remove the line breaks? It makes it harder to review that way

**Comment by XC-** [comment]
Certainly. Will do that tomorrow!

**Comment by XC-** [comment]
@gr2m Sorry for the delay. Busier days than expected, but now the line breaks are removed :)

**Review by gr2m — APPROVED** [review]
This is great, thank you so much 💐

**Pull request merged**
