### PR TITLE
Doc cleanup

### PR DESCRIPTION
**Pull request by esciara**
Includes:

- docs(recipes): cleaned doc and navigation
  - Corrected inconsistancies between the sidebar and the actual pages. Remove non existing pages. 
  - Clarified status of "Package managers and languages" to "to be completed".
- docs: repared broken links to "CI configuration recipes"
- docs: cleaned "Developer guide" section navigation
- docs: synched README.md and SUMMARY.md

Also added my (Jetbrains) IDE files to `.gitignore`.

### CODE REVIEW

**Comment by esciara** [comment]
As a note: I don't know how to test the doc locally to see whether all navigations are correct. If you can enlighten me!

**Comment by gr2m** [comment]
> As a note: I don't know how to test the doc locally to see whether all navigations are correct. If you can enlighten me!

That is a very good question. I just looked into it myself and found that these instructions work https://til.secretgeek.net/gitbook/use_gitbook_locally.html. Could you maybe add them to CONTRIBUTING.md?

**Comment by esciara** [comment]
> That is a very good question. I just looked into it myself and found that these instructions work https://til.secretgeek.net/gitbook/use_gitbook_locally.html. Could you maybe add them to CONTRIBUTING.md?

@gr2m  #1247 😜

**Comment by pvdlg** [comment]
The goal of the `README.md` files in each directory is to give users a table of content when they navigate the doc on GitHub.
So when you go to `https://github.com/semantic-release/semantic-release/tree/master/docs/03-recipes` you would have a table of content.

Why was it removed?

**Pull request merged**
