### PR TITLE
Extract npm and github publish to plugins

### LINKED ISSUE #215: Deployment without npm registry
Hello there,

I am currently using semantic release for one of my libraries ([leifg/formulon](https://github.com/leifg/formulon) if you're interested).

But I also use it for a frontend project which is not released on the npm registry ([leifg/formulon-frontend](https://github.com/leifg/formulon-frontend)). I just replaced `npm publish` with `npm run deploy` and it works perfectly.

I ran into the problem that the CI system expects an NPM_TOKEN and fails if it doesn't. An easy workaround is just to set the env variable to something irrelevant but I don't feel that this is a good solution.

Is there a better way?

### LINKED ISSUE #244: Don't publish for private packages?
For https://github.com/atlassian/lerna-semantic-release, there'd be a use case where we don't want to publish private packages. Is this behaviour that would be accepted in a PR?

If not, we'll just build it in lerna-semantic-release

### LINKED ISSUE #425: semantic-release post fails to publish release notes.
I've been trying to setup semantic-release in to one of my projects and failed with the above error. So i created a new repository to make sure this is not something related to my previous project. 

I have this new github repository https://github.com/kasunkv/sem-rel
I used semantic-release-cli to set the initial configuration for semantic-release. The setup process went without any issues. Then i used commitizen  and cz-conventional-changelog for my commit conventions. The package.json and the travis.yml files look like this.

**package.json**
```
{
  "name": "sem-rel",
  "version": "0.0.0-development",
  "description": "Sample project to test semantic releases",
  "main": "index.js",
  "scripts": {
    "commit": "git cz",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/kasunkv/sem-rel.git"
  },
  "keywords": [
    "semantic",
    "release"
  ],
  "author": "Kasun Kodagoda",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/kasunkv/sem-rel/issues"
  },
  "homepage": "https://github.com/kasunkv/sem-rel#readme",
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
  "devDependencies": {
    "commitizen": "^2.9.6",
    "cz-conventional-changelog": "^2.0.0",
    "semantic-release": "^7.0.2"
  }
}
```
**.travis.yml**
```
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

```

The commits i made can be seen here: https://github.com/kasunkv/sem-rel/commits/master

When i did the initial build with travis, the release went without any issues. the `semantic-release pre` and `semantic-release post` commands was successful and a new release got created in github.

But when i did some more commits to change the version number and then run the build, the `semantic-release post` step fails with the following error message.

```
+ sem-rel@1.0.0
semantic-release WARN invalid config loglevel="notice"
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Reference already exists","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}]
semantic-release ERR! post   message: '{"message":"Reference already exists","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}',
semantic-release ERR! post   code: 422,
semantic-release ERR! post   status: 'Unprocessable Entity',
semantic-release ERR! post   headers: 
semantic-release ERR! post    { server: 'GitHub.com',
semantic-release ERR! post      date: 'Tue, 29 Aug 2017 15:13:11 GMT',
semantic-release ERR! post      'content-type': 'application/json; charset=utf-8',
semantic-release ERR! post      'content-length': '121',
semantic-release ERR! post      connection: 'close',
semantic-release ERR! post      status: '422 Unprocessable Entity',
semantic-release ERR! post      'x-ratelimit-limit': '5000',
semantic-release ERR! post      'x-ratelimit-remaining': '4588',
semantic-release ERR! post      'x-ratelimit-reset': '1504020483',
semantic-release ERR! post      'x-oauth-scopes': 'repo, read:org, user:email, repo_deployment, repo:status, write:repo_hook',
semantic-release ERR! post      'x-accepted-oauth-scopes': '',
semantic-release ERR! post      'x-github-media-type': 'github.v3; format=json',
semantic-release ERR! post      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
semantic-release ERR! post      'access-control-allow-origin': '*',
semantic-release ERR! post      'content-security-policy': 'default-src \'none\'',
semantic-release ERR! post      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
semantic-release ERR! post      'x-content-type-options': 'nosniff',
semantic-release ERR! post      'x-frame-options': 'deny',
semantic-release ERR! post      'x-xss-protection': '1; mode=block',
semantic-release ERR! post      'x-runtime-rack': '0.369359',
semantic-release ERR! post      'x-github-request-id': 'A098:0DF5:27EED9A:579E468:59A58486' } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sem-rel@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sem-rel@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-08-29T15_13_11_189Z-debug.log
```

This was the exact same error i got on my other project. I can not figure out what i am doing wrong here. Some help would be much appreciated.
Travis Build: https://travis-ci.org/kasunkv/sem-rel

### LINKED ISSUE #459: Hardcoded fallbackTags dist-tag
The `fallbackTags` is hardcoded to `next` [here](https://github.com/semantic-release/semantic-release/blob/caribou/src/index.js#L34). It's used [there](https://github.com/semantic-release/last-release-npm/blob/master/index.js#L27).

It seems that when we configure a dist-tag in `publishConfig` or `.npmrc` and there is no published release on that dist-tag yet, we fallback to the last release on `latest` but only if the dist-tag configured is `next`. Should we always fallback to `latest`, no matter the dist-tag configured?

Am I missing something?

/cc @gr2m

### LINKED ISSUE #465: use without npm
I'm a bit confused about how/if I can use this without publishing to NPM. I'm using this for a private project. The first release seemed to work fine 1.0.0, but then 4 commits later, there were still no releases made even after successful CI builds.

Is this because I have nothing published on NPM? Does it refer to the version number in NPM to generate the latest version number? If so, how can I get around this?

UPDATE: I've modified my setup to use a getLastRelease plugin that gets it from git tags instead. I still get the same thing, after the first publication of a release, it shows 'x commits have been made on master since this release' but no new releases are made. the versions are all just on 1.0.0 or 2.0.0.
after using the plugin the version number was bumped to 2.0.0.

### LINKED ISSUE #484: Customize release/publish via plugins
Currently `semantic-release` is really tied to npm publish and Github releases, but ideally we should be able to support any platform.

A good solution for that would be to use our plugin mechanism.
In order to support any publish/release type we could add a new type of Plugins, `publish`, that would a pipeline (similar to `verifyConditions` and `verifyRelease`).

We would create the following plugins:
- `npm-publish` that would:
    - Receive the `nextRelease` as parameter
    - Read the npm conf from `package.json` and `.npmrc`
    - Update the version in `package.json` and `npm-shrinkwrap.json`
    - Call `npm publish`
- `github-release` that would:
    - Receive the release `notes` and the `nextRelease`
    - Get the github configuration and auth from `package.json` and environment variables
    - Publish a release, create a tag and optionally upload binaries files to github release

That would completely remove npm and github dependencies in the main `semantic-release`.

The configuration would look like this:
```json
"release": {
  "publish": ["@semantic-release/npm-publish", "@semantic-release/github-release", "other-plugin"]
}
```
We could use by default `@semantic-release/npm-publish` and `@semantic-release/github-release`.

That would allow to solve the numerous issues that request to use `semantic-release` without publishing on npm. It would also allow to easily create plugins for anything else: [apm](https://github.com/atom/apm), Github Pages, Gitlab, Bitbucket etc...

We could even create a simple plugin that just run command set in the configuration.

### PR DESCRIPTION
**Pull request by pvdlg**
- Add a new plugin type: `publish`
- Add support for multi-plugin. A plugin module can now return an object with a property for each plugin type
- Uses by default [npm](https://github.com/semantic-release/npm) and [github](https://github.com/semantic-release/github) in addition of Travis for the verify condition plugin
- Uses by default [npm](https://github.com/semantic-release/npm) and [github](https://github.com/semantic-release/github) for the publish plugin
- `gitTag` if one can be found is passed to `generateNotes` for both `lastRelease` and `nextRelease`
- `semantic-release` now verifies the plugin configuration (in the `release` property of `package.json`) and throws an error if it's invalid
- `semantic-release` now verifies each plugin output and will throw an error if a plugin returns an unexpected value.

To be merged only when https://github.com/semantic-release/github is released.

Fix #484, Fix #459, Fix #504, Fix #465, Fix #425, Fix #215, Fix #244

### CODE REVIEW

**Comment by gr2m** [comment]
I’m wondering about the note in the 2nd breaking change:

> the `npm` parameter is not passed to any plugin anymore. Each plugin have to read `.npmrc` if they needs to.

is there a package you are using to read out the npm rc auth? If yes, maybe we can recommend it in the release notes? No need to update commits, we can update release notes later

**Comment by pvdlg** [comment]
> is there a package you are using to read out the npm rc auth? If yes, maybe we can recommend it in the release notes? No need to update commits, we can update release notes later

I'm using https://github.com/kevva/npm-conf [here](https://github.com/semantic-release/npm/blob/master/lib/get-last-release.js#L3)

I can update the commit as I have to reference https://github.com/semantic-release/github version 1.0.0 when it's released

**Comment by felixfbecker** [comment]
Isn't npm-conf deprecated?

**Comment by pvdlg** [comment]
[npmconf](https://github.com/npm/npmconf) is deprecated. [npm-conf](https://github.com/kevva/npm-conf) is not.

**Comment by felixfbecker** [comment]
Could you give an example how to use an arbitrary shell command as a publish step? E.g. `docker push`, `vsce publish` etc

**Comment by pvdlg** [comment]
> Could you give an example how to use an arbitrary shell command as a publish step? E.g. docker push, vsce publish etc

That is not possible yet. I'm working on a plugin that would allow to do that.

**Comment by felixfbecker** [comment]
Do existing plugins like https://github.com/finom/last-release-git sill work with 10.0.0?

Btw, thank you for all the work @pvdlg! These updates are very exciting.

**Comment by pvdlg** [comment]
I cannot tell you about https://github.com/finom/last-release-git
But https://github.com/semantic-release/last-release-git-tag does works with `10.0.0`

**Comment by felixfbecker** [comment]
Even better!

**Pull request merged**
