### PR TITLE
Contributing guidelines and issue template

### LINKED ISSUE #413: Document test setup for scenario test
Follow up for https://github.com/semantic-release/semantic-release/pull/408#issuecomment-322029479, ping @zetaron

The scenario tests need a local CouchDB to be in admin party mode (no admin user configured) and be accessible at port `15986`. I’m pretty sure that is the default port when running CouchDB with Docker. I’m no Docker expert though, if someone could give this a try, I’d appreciate it  <3

### LINKED ISSUE #441: Add a CONTRIBUTING.md
It would be great to add a CONTRIBUTING.md guide to help contributors.

Here is the section we could have:
- [ ] Mention stackoverflow / gitter for troubleshooting help
- [ ] How to open an issue (search in the tracker before, add link to CI logs, add relevant info etc..)
- [ ] How to request a new feature (search in the issue tracker and PRs, explain use case etc..)
- [ ] How to submit a PR (fork, commit, rebase etc...)
- [ ] Commit message guidelines (guidelines, explain how to use commitizen to make contributors life easier)
- [ ] Coding rules (mention eslint-config-standard and prettier, suggest to install IDE integration for [prettier](https://prettier.io/docs/en/editors.html) and [eslint](https://eslint.org/docs/user-guide/integrations#editors))
- [ ] Maybe define an issue triage process (label, workflow etc...)

Here is a few good examples:
- [angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)
- [hoodie](https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md)
- [eslint](https://eslint.org/docs/developer-guide/contributing/)
- [karma](http://karma-runner.github.io/1.0/dev/making-changes.html)

In addition I think it would be helpful to enforce a linear git history. See : http://www.bitsnbites.eu/a-tidy-linear-git-history/ and http://www.bitsnbites.eu/git-history-work-log-vs-recipe/ for more details

That would be really great for `semantic-release` as we create releases and changelogs based on commit history. This way we would have a clean, linear git history that matches the release and changelog.

Rebasing a PR might be a bit difficult/confusing for contributors sometimes though. But I think we could explain in CONTRIBUTING.md how to do it and encourage contributors to check the "Allow edits from maintainers" checkbox so we can do it ourselves.

/cc @gr2m

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #441, Fix #413

### CODE REVIEW

**Comment by gr2m** [comment]
we could take advantage of an undocumented GitHub feature: multiple issue templates. See this repository for a demonstration: https://github.com/clarkbw/team-plates/ :) We can also do it in a follow up PR?

**Comment by pvdlg** [comment]
> we could take advantage of an undocumented GitHub feature: multiple issue templates. See this repository for a demonstration: https://github.com/clarkbw/team-plates/ :)

Is it really a feature? When I open an issue on this repo I just see the link in the template.
Am I missing something?

**Comment by pvdlg** [comment]
Never mind I get it now.

**Comment by gr2m** [comment]
try one of these:

1. Bugs: https://github.com/clarkbw/team-plates/issues/new?template=bug.md
2. Feature Requests: https://github.com/clarkbw/team-plates/issues/new?template=feature.md

**Pull request merged**
