### PR TITLE
fix(log-repo): use the original form of the repo url to remove the need to mask credentials

### LINKED ISSUE #2449: Credentials are revealed in log
## Current behavior

Credentials are revealed in the logs (see example below):
`Run automated release from branch master on repository https://username:password@bitbucket.example.com/repo.git`

## Expected behavior

Credentials should be hidden (see example below);
`Run automated release from branch master on repository https://[secret]@bitbucket.example.com/repo.git`

## Environment

- **semantic-release** version: 19.0.2
- CI environment: TeamCity
- Plugins used: commit-analyzer, release-notes-generator, changelog, exec, git
- **semantic-release** configuration:
`"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      [
        "@semantic-release/release-notes-generator",
        {
          "preset": "angular",
          "linkCompare": false,
          "linkReferences": false
        }
      ],
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "docs/CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/exec",
        {
          "prepareCmd": "echo ##teamcity[buildNumber '${nextRelease.version}']"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": [
            "docs/CHANGELOG.md"
          ]
        }
      ]
    ]`
- CI logs: see above for the relevant log entry

We are using semantic-release in combination with Bitbucket Server. Credentials are passed via environment variable BITBUCKET_TOKEN_BASIC_AUTH.

AFAIK this should be the relevant line that reveals (logs) the sensitive data:
https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/index.js#L78

### PR DESCRIPTION
**Pull request by travi**
fixes #2449

### CODE REVIEW

**Review by gr2m — APPROVED** [review]

**Comment by travi** [comment]
i have been unable to reproduce the test failures locally in either node v16 or v14

**Comment by travi** [comment]
it looks like all of the failures are in `test/integration.test.js`. i wonder if something has changed with how that is able to execute on actions recently.

**Comment by gr2m** [comment]
me neither :( 

Anyone else has any luck?

**Comment by travi** [comment]
i dont have a great explanation, but i updated the lockfile for #2447 to get it passing and rebased this branch with the mainline after merging that PR to pickup those lockfile changes, which enabled this change to pass the build 🤷🏼

**Comment by Gam3356** [comment]
Check IP

**Pull request merged**
