### PR TITLE
fix(cli): use unmodified PATH when checking git version

### PR DESCRIPTION
**Pull request by patrickleet**
See conversation at end of the issue:
https://github.com/semantic-release/npm/issues/143

And:
https://github.com/sindresorhus/execa/issues/196

### CODE REVIEW

**Comment by patrickleet** [comment]
I worry this means other parts of semantic-release could potentially be using the wrong git version, aside from a version check where version 2 is actually required unless `preferLocal: false` is added in other places as well.

**Comment by patrickleet** [comment]
still using my temp package I published to get around this when using semantic-release with jenkins x

**Comment by mateodelnorte** [comment]
Experiencing the same issue. An approval and merge on this would be great.

**Comment by patrickleet** [comment]
Yea, this affects everyone using Jenkins X who wants to use semantic-release

**Comment by gr2m** [comment]
Can you resolve the conflict please?

**Comment by pvdlg** [comment]
Changing that value only there won't fix the problem...It will just use the correct version when doing the version check not when using `git` anywhere else.

execa@2.0.0 use `false` as the default so that should solve the problem.
We'll move to execa@2.0.0 in v16.0.0 (as it require us to upgrade the minimum version of Node that we support.)

**Comment by pvdlg** [comment]
execa@2.0.0 updated here: https://github.com/semantic-release/semantic-release/pull/1217

**Pull request closed without merging**
