### PR TITLE
feat: Support staying on v0.x.y with --unstable

### PR DESCRIPTION
**Pull request by dcodeIO**
As a follow-up to https://github.com/semantic-release/semantic-release/issues/1507#issuecomment-643552928 this is an initial draft implementation to opt-in to keep versions in the `v0.x.y` range.

Context is that we are building what's essentially a [TS to Wasm compiler](https://github.com/AssemblyScript/assemblyscript), with the underlying tech being pretty much still in flux, so we'd prefer to keep the version below a `v1` while certain critical language features are not yet available and do a `v1` once the project is ready to be perceived as something reasonably finished. Yet we'd like to switch to using semantic-release.

Idea is to specify the `--unstable` option as long as a `v1` is not wanted, and remove it again once a `v1` is ready. As such there are no functional changes for existing users, and it's fully opt-in.

~~Coincidentally, I also fixed linting and testing on Windows by making Git checkout with `\n` instead of `\r\n` line endings.~~ addressed in https://github.com/semantic-release/semantic-release/pull/1575

Is this something you'd be willing to support officially? And yeah, from the existing issues I learned that this is a somewhat sensitive topic :)

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Daniel! I'll have to discuss this with Pierre, who is not available right now, so please give us a moment.

> Coincidentally, I also fixed linting and testing on Windows by making Git checkout with `\n` instead of `\r\n` line endings.

Could you create a separate PR for this, so that we can discuss it separately?

**Comment by dcodeIO** [comment]
Synched again on top of master. Have been using the feature in production for a while now without any issues. Did you guys have a chance to discuss yet? :)

**Comment by gr2m** [comment]
not yet, sorry.  Thank you for keeping the pull request up-to-date, it does look pretty good to me. Could you update docs as well?

**Comment by gr2m** [comment]
We talked once more about the topic, but our conclusion remains that this is much more complicated than it looks. Adding this feature will likely create lots of more issues, and we are having a hard time supporting semantic-release as is today. 

Sorry :( 

We will not be implementing it in semantic-release. And we have an alternative solution that is supported today: using pre-release channels, see https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0-0-1

**Comment by dcodeIO** [comment]
Ok. But thanks for looking into it!

**Pull request closed without merging**
