### PR TITLE
fix(marked): reverted upgrade to v3

### PR DESCRIPTION
**Pull request by travi**
since marked v3 requires node v12

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
should we add `marked` to be ignored by renovate? We'd need to configure it in `package.json`'s `"renovate"` object

**Comment by travi** [comment]
> should we add `marked` to be ignored by renovate?

i'd rather renovate keep us aware that there is an upgrade, but fail the build if it would be incompatible. it looks like the build is failing properly now, but i missed something else that isnt compatible with node v10. tracking that piece down now

**Comment by travi** [comment]
i'm reverting the switch to use `ls-engines` because it revealed that we have a few other engines compatibility issues to resolve before we can make that change. i will follow up with those adjustments in a separate PR

**Review by gr2m — APPROVED** [review]

**Comment by ThibaultVlacich** [comment]
Wouldn't it be better to allow both versions? `^2.0.0 || ^3.0.0`

**Pull request merged**
